name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  qualite-et-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Initialiser PHP avec PCOV
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, ctype, iconv, sqlite3, pcov
          tools: composer
          coverage: pcov

      - name: Installer les dépendances
        run: composer install --prefer-dist --no-interaction

      - name: Vérifier le respect du style de code (Linting)
        run: ./vendor/bin/pint --test

      - name: Préparer la configuration
        run: cp .env.example .env

      - name: Générer la clé d'application
        run: php artisan key:generate

      - name: Exécuter les tests avec calcul de couverture
        run: ./vendor/bin/phpunit --coverage-html build/coverage-report

      - name: Archiver le rapport de couverture en tant qu'Artefact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: rapport-couverture-html
          path: build/coverage-report/
          retention-days: 7
